// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZd2x2LzDpSYnGOuUhjY1rcnG0VQOpfNU',
    appId: '1:807229341646:web:09e8d65cadc151787b759f',
    messagingSenderId: '807229341646',
    projectId: 'avantefoods-ce668',
    authDomain: 'avantefoods-ce668.firebaseapp.com',
    storageBucket: 'avantefoods-ce668.firebasestorage.app',
    measurementId: 'G-E5MX20657S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzwSyRATqUQnY6cR4XOYtRY8e7uHyZHec',
    appId: '1:807229341646:android:a87da273b07bd7727b759f',
    messagingSenderId: '807229341646',
    projectId: 'avantefoods-ce668',
    storageBucket: 'avantefoods-ce668.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa9mqObVH7yP3DAme3nShBX3BfTkSqpHg',
    appId: '1:807229341646:ios:1eed601a7dca4f207b759f',
    messagingSenderId: '807229341646',
    projectId: 'avantefoods-ce668',
    storageBucket: 'avantefoods-ce668.firebasestorage.app',
    iosBundleId: 'com.example.customMpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa9mqObVH7yP3DAme3nShBX3BfTkSqpHg',
    appId: '1:807229341646:ios:1eed601a7dca4f207b759f',
    messagingSenderId: '807229341646',
    projectId: 'avantefoods-ce668',
    storageBucket: 'avantefoods-ce668.firebasestorage.app',
    iosBundleId: 'com.example.customMpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZd2x2LzDpSYnGOuUhjY1rcnG0VQOpfNU',
    appId: '1:807229341646:web:0b13db436bcecac47b759f',
    messagingSenderId: '807229341646',
    projectId: 'avantefoods-ce668',
    authDomain: 'avantefoods-ce668.firebaseapp.com',
    storageBucket: 'avantefoods-ce668.firebasestorage.app',
    measurementId: 'G-YSC56LBGKW',
  );
}
